"""
email_sender.py — Email Dispatcher for ClientIQ
Sends the generated Excel report as an attachment via Gmail SMTP (port 587 / STARTTLS).

Required .env variables:
  EMAIL_ADDRESS  — Gmail address used to send (e.g. yourapp@gmail.com)
  EMAIL_PASSWORD — Gmail App Password (16-char code, NOT your real password)
"""

import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass


def send_email(excel_filename: str, company_info: dict,
               recipient_emails: list) -> bool:
    """
    Send the Excel report to one or more email addresses.

    Args:
        excel_filename   : Path to the .xlsx report file
        company_info     : Dict with keys: Company, Website, Industry, Location
        recipient_emails : List of recipient email addresses

    Returns:
        True on success, False on failure.

    Raises:
        EnvironmentError : If EMAIL_ADDRESS or EMAIL_PASSWORD are missing.
        FileNotFoundError: If excel_filename does not exist.
    """
    sender_email    = os.getenv("EMAIL_ADDRESS", "").strip()
    sender_password = os.getenv("EMAIL_PASSWORD", "").strip()

    if not sender_email or not sender_password:
        raise EnvironmentError(
            "EMAIL_ADDRESS and EMAIL_PASSWORD must be set in your .env file. "
            "Use a Gmail App Password — see README for setup instructions."
        )

    if not os.path.exists(excel_filename):
        raise FileNotFoundError(
            f"Excel report not found at: {excel_filename}"
        )

    company_name = company_info.get("Company",  "Unknown")
    industry     = company_info.get("Industry", "N/A")
    website      = company_info.get("Website",  "N/A")
    location     = company_info.get("Location", "N/A")

    # ── Build message ──────────────────────────────────────────
    msg = MIMEMultipart()
    msg["From"]    = sender_email
    msg["To"]      = ", ".join(recipient_emails)
    msg["Subject"] = (
        f"🔍 ClientIQ Report — {company_name} | "
        f"{datetime.now().strftime('%B %d, %Y')}"
    )

    # ── Plain-text email body ──────────────────────────────────
    body = f"""
Hello,

The ClientIQ Business Intelligence Agent has completed its research.
Please find the full report attached.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📊 REPORT SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🏢 Company     : {company_name}
🌐 Website     : {website}
🏭 Industry    : {industry}
📍 Location    : {location}
📅 Generated   : {datetime.now().strftime("%B %d, %Y %I:%M %p")}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The attached Excel report contains:
  ✅ Company Overview
  ✅ Brand Analysis
  ✅ Website & SEO Analysis
  ✅ Competitor Analysis
  ✅ SEO & Digital Presence
  ✅ Target Audience
  ✅ SWOT Analysis
  ✅ Market Opportunities
  ✅ Strategic Recommendations
  ✅ Final Business Assessment

This report was fully generated by ClientIQ AI Agent.

Best regards,
ClientIQ — AI Business Intelligence Agent
"""
    msg.attach(MIMEText(body, "plain"))

    # ── Attach Excel file ──────────────────────────────────────
    with open(excel_filename, "rb") as attachment:
        part = MIMEBase("application", "octet-stream")
        part.set_payload(attachment.read())

    encoders.encode_base64(part)
    part.add_header(
        "Content-Disposition",
        f"attachment; filename={os.path.basename(excel_filename)}"
    )
    msg.attach(part)

    # ── Send via Gmail SMTP (port 587, STARTTLS) ───────────────
    try:
        print(f"📧 Connecting to Gmail SMTP...")
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, recipient_emails, msg.as_string())
        server.quit()
        print(f"✅ Email sent to: {', '.join(recipient_emails)}")
        return True
    except Exception as e:
        print(f"❌ Email failed: {str(e)}")
        raise
