"""
report.py -- Report Formatter & File Saver for ClientIQ
Generates professional Markdown reports from agent research results.
Supports both modes:
  - Company BI Report  (build_report)
  - Startup Research Report (build_startup_report)
"""

import os
from datetime import datetime
from rich.console import Console
from rich.panel import Panel
from rich.markdown import Markdown

console = Console()


def build_report(company_info: dict, sections: dict) -> str:
    """
    Assemble all researched sections into a structured Markdown BI report.
    Returns the full report as a string.
    """
    company_name = company_info.get("company_name", "Unknown Company")
    website_url  = company_info.get("website_url", "")
    industry     = company_info.get("industry", "")
    generated_at = datetime.now().strftime("%B %d, %Y — %H:%M")

    # ─── Header ─────────────────────────────────────────────
    report = f"""# BUSINESS INTELLIGENCE REPORT
**Company:** {company_name}
**Industry:** {industry}
**Website:** {website_url}
**Generated by:** ClientIQ — AI Business Intelligence Agent
**Date:** {generated_at}

---

> *This report was autonomously generated using live internet research. 
> All data is sourced from publicly available information.*

---

## 1. Company Overview

{sections.get("company_overview", "Not available.")}

---

## 2. Brand Analysis

{sections.get("brand_analysis", "Not available.")}

---

## 3. Website Analysis

{sections.get("website_analysis", "Not available.")}

---

## 4. Competitor Analysis

{sections.get("competitor_analysis", "Not available.")}

---

## 5. SEO & Digital Presence

{sections.get("seo_and_digital_presence", "Not available.")}

---

## 6. Target Audience

{sections.get("target_audience", "Not available.")}

---

## 7. SWOT Analysis

{sections.get("swot_analysis", "Not available.")}

---

## 8. Market Opportunities

{sections.get("market_opportunities", "Not available.")}

---

## 9. Strategic Recommendations

{sections.get("strategic_recommendations", "Not available.")}

---

## 10. Final Business Assessment

{sections.get("final_assessment", "Not available.")}

---

*— End of Report — Generated by ClientIQ*
"""

    return report


def save_report(report: str, company_name: str, output_dir: str = ".") -> str:
    """
    Save the report as a Markdown file.
    Returns the file path.
    """
    # Sanitize company name for filename
    safe_name = "".join(c if c.isalnum() or c in " _-" else "_"
                        for c in company_name).strip().replace(" ", "_")
    timestamp  = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename   = f"BI_Report_{safe_name}_{timestamp}.md"
    filepath   = os.path.join(output_dir, filename)

    os.makedirs(output_dir, exist_ok=True)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report)

    return filepath


def display_report_summary(company_info: dict, sections: dict):
    """
    Print a beautiful summary of the completed report to the terminal.
    """
    company_name = company_info.get("company_name", "Unknown Company")

    console.print("\n")
    console.print(Panel(
        f"[bold green]✓ Report Complete![/]\n\n"
        f"[bold]{company_name}[/] — Business Intelligence Report\n\n"
        f"Sections researched: [cyan]{len(sections)}[/]\n"
        f"Research method: [cyan]Live internet data via ReAct agent[/]",
        title="[bold white]ClientIQ Report Summary[/]",
        border_style="green",
        padding=(1, 4)
    ))

    # Show brief snippet from each section
    section_names = {
        "company_overview":        "1. Company Overview",
        "brand_analysis":          "2. Brand Analysis",
        "website_analysis":        "3. Website Analysis",
        "competitor_analysis":     "4. Competitor Analysis",
        "seo_and_digital_presence":"5. SEO & Digital Presence",
        "target_audience":         "6. Target Audience",
        "swot_analysis":           "7. SWOT Analysis",
        "market_opportunities":    "8. Market Opportunities",
        "strategic_recommendations":"9. Strategic Recommendations",
        "final_assessment":        "10. Final Assessment",
    }

    console.print("\n[bold]Section Status:[/]")
    for key, display_name in section_names.items():
        content = sections.get(key, "")
        status  = "[green]OK[/]" if content and len(content) > 50 else "[red]--[/]"
        preview = content[:60].replace("\n", " ") + "..." if content else "Empty"
        console.print(f"  {status} {display_name}")
        console.print(f"     [dim]{preview}[/]")


# ═══════════════════════════════════════════════════════════
# STARTUP REPORT BUILDER
# ═══════════════════════════════════════════════════════════

def build_startup_report(idea_info: dict, sections: dict) -> str:
    """
    Assemble all startup research sections into a Markdown report.
    Returns the full report as a string.
    """
    business_idea  = idea_info.get("business_idea", "Unknown Business Idea")
    industry       = idea_info.get("industry", "")
    target_market  = idea_info.get("target_market", "")
    geography      = idea_info.get("geography", "")
    business_model = idea_info.get("business_model", "")
    unique_angle   = idea_info.get("unique_angle", "")
    generated_at   = datetime.now().strftime("%B %d, %Y -- %H:%M")

    report = f"""# STARTUP RESEARCH REPORT
**Business Idea:** {business_idea}
**Industry:** {industry}
**Target Market:** {target_market}
**Geography:** {geography}
**Business Model:** {business_model}
**Unique Angle:** {unique_angle}
**Generated by:** ClientIQ -- Startup Research Agent
**Date:** {generated_at}

---

> *This report was autonomously generated using live internet research.*
> *All data is sourced from publicly available information.*
> *Use this as a starting point for your business planning, not as financial advice.*

---

## 1. Market Landscape

{sections.get("market_landscape", "Not available.")}

---

## 2. Competitor Benchmarking

{sections.get("competitor_benchmarking", "Not available.")}

---

## 3. Target Customer Profile

{sections.get("customer_profile", "Not available.")}

---

## 4. Business Model & Revenue Options

{sections.get("business_model_options", "Not available.")}

---

## 5. Tech Stack & Tools Required

{sections.get("tech_and_tools", "Not available.")}

---

## 6. Marketing Channels & Customer Acquisition

{sections.get("marketing_channels", "Not available.")}

---

## 7. Risk Analysis

{sections.get("risk_analysis", "Not available.")}

---

## 8. SWOT Analysis (New Entrant Perspective)

{sections.get("startup_swot", "Not available.")}

---

## 9. Go-To-Market Strategy

{sections.get("go_to_market_strategy", "Not available.")}

---

## 10. Startup Viability Assessment

{sections.get("viability_assessment", "Not available.")}

---

*-- End of Startup Research Report -- Generated by ClientIQ*
"""
    return report


def save_startup_report(report: str, business_idea: str, output_dir: str = ".") -> str:
    """Save the startup report as a Markdown file. Returns the file path."""
    safe_name = "".join(
        c if c.isalnum() or c in " _-" else "_" for c in business_idea
    ).strip().replace(" ", "_")[:40]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename  = f"Startup_Report_{safe_name}_{timestamp}.md"
    filepath  = os.path.join(output_dir, filename)
    os.makedirs(output_dir, exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report)
    return filepath


def display_startup_summary(idea_info: dict, sections: dict):
    """Print terminal summary for startup report."""
    business_idea = idea_info.get("business_idea", "Your Business Idea")

    console.print("\n")
    console.print(Panel(
        f"[bold green]Startup Research Complete![/]\n\n"
        f"[bold]{business_idea}[/]\n\n"
        f"Sections researched: [cyan]{len(sections)}[/]\n"
        f"Research method: [cyan]Live internet data via ReAct agent[/]",
        title="[bold white]ClientIQ -- Startup Report Summary[/]",
        border_style="yellow",
        padding=(1, 4)
    ))

    section_names = {
        "market_landscape":      "1. Market Landscape",
        "competitor_benchmarking":"2. Competitor Benchmarking",
        "customer_profile":      "3. Target Customer Profile",
        "business_model_options":"4. Business Model & Revenue",
        "tech_and_tools":        "5. Tech Stack & Tools",
        "marketing_channels":    "6. Marketing Channels",
        "risk_analysis":         "7. Risk Analysis",
        "startup_swot":          "8. SWOT Analysis",
        "go_to_market_strategy": "9. Go-To-Market Strategy",
        "viability_assessment":  "10. Viability Assessment",
    }

    console.print("\n[bold]Section Status:[/]")
    for key, display_name in section_names.items():
        content = sections.get(key, "")
        status  = "[green]OK[/]" if content and len(content) > 50 else "[red]--[/]"
        preview = content[:60].replace("\n", " ") + "..." if content else "Empty"
        console.print(f"  {status} {display_name}")
        console.print(f"     [dim]{preview}[/]")

